// Static map from bot id → generated robot portrait URL.
// Each of the 12 bots has its own distinct portrait. Images live in
// public/bots/{bot-id}.png and are generated by
// scripts/generate-bot-avatars.ts. Re-run that script to refresh.

const BOT_IMAGES: Record<string, string> = {
  "liquidation-lizard": "/bots/liquidation-lizard.png",
  "liquidation-lizard-jr": "/bots/liquidation-lizard-jr.png",
  "funding-phoebe": "/bots/funding-phoebe.png",
  "funding-phoebe-lite": "/bots/funding-phoebe-lite.png",
  "mean-revert-mike": "/bots/mean-revert-mike.png",
  "mean-revert-mike-patient": "/bots/mean-revert-mike-patient.png",
  "momo-max": "/bots/momo-max.png",
  "momo-max-aggressive": "/bots/momo-max-aggressive.png",
  "vol-vector": "/bots/vol-vector.png",
  "vol-vector-hair-trigger": "/bots/vol-vector-hair-trigger.png",
  "boomer-trend": "/bots/boomer-trend.png",
  "boomer-trend-wide": "/bots/boomer-trend-wide.png",
};

export function avatarImageForBot(botId: string): string | null {
  return BOT_IMAGES[botId] ?? null;
}
