// Static map from bot id → generated robot portrait URL.
// Images live in public/bots/{bot-id}.png and are generated by
// scripts/generate-bot-avatars.ts. Re-run that script to refresh
// (defaults to the 4 active v4 bots; pass keys on CLI for others).
//
// Why a static map and not a fs.existsSync check: the API route that
// reads this runs on every request — a fs probe per bot per request
// would hit disk needlessly, and a dev-vs-prod asset-pipeline mismatch
// could lead to false negatives. The map is authoritative.

const BOT_IMAGES: Record<string, string> = {
  // ── v4 active roster ──────────────────────────────────────────
  whale: "/bots/whale.png",
  native: "/bots/native.png",
  "funding-sniper": "/bots/funding-sniper.png",
  pulse: "/bots/pulse.png",
  bullion: "/bots/bullion.png",
  atlas: "/bots/atlas.png",

  // ── Dormant arena-era bots (kept for revival) ─────────────────
  vulture: "/bots/vulture.png",
  contrarian: "/bots/contrarian.png",
  "whale-shadow": "/bots/whale-shadow.png",
  "grok-trader": "/bots/grok-trader.png",
  "claude-trader": "/bots/claude-trader.png",

  // ── Legacy 12 (pre-v3 personas) ───────────────────────────────
  "liquidation-lizard": "/bots/liquidation-lizard.png",
  "liquidation-lizard-jr": "/bots/liquidation-lizard-jr.png",
  "funding-phoebe": "/bots/funding-phoebe.png",
  "funding-phoebe-lite": "/bots/funding-phoebe-lite.png",
  "mean-revert-mike": "/bots/mean-revert-mike.png",
  "mean-revert-mike-patient": "/bots/mean-revert-mike-patient.png",
  "momo-max": "/bots/momo-max.png",
  "momo-max-aggressive": "/bots/momo-max-aggressive.png",
  "vol-vector": "/bots/vol-vector.png",
  "vol-vector-hair-trigger": "/bots/vol-vector-hair-trigger.png",
  "boomer-trend": "/bots/boomer-trend.png",
  "boomer-trend-wide": "/bots/boomer-trend-wide.png",
};

export function avatarImageForBot(botId: string): string | null {
  return BOT_IMAGES[botId] ?? null;
}
