// scripts/seed-bots.ts
import { db } from "@/lib/db";
import { bots } from "@/lib/db/schema";

const ROWS = [
  {
    id: "liquidation-lizard",
    parentId: null,
    name: "Liquidation Lizard",
    avatarEmoji: "🦎",
    personaVoiceKey: "liquidation-lizard",
    strategyKey: "liquidation-lizard",
    config: {
      minLiqNotionalUsd: 50_000,
      leverage: 50,
      exitFavorablePct: 0.005,
      maxHoldMs: 90_000,
    },
    status: "paper",
  },
  {
    id: "liquidation-lizard-jr",
    parentId: "liquidation-lizard",
    name: "Liquidation Lizard Jr.",
    avatarEmoji: "🦎",
    personaVoiceKey: "liquidation-lizard",
    strategyKey: "liquidation-lizard-jr",
    config: {
      minLiqNotionalUsd: 15_000,
      leverage: 50,
      exitFavorablePct: 0.003,
      maxHoldMs: 60_000,
    },
    status: "paper",
  },
  {
    id: "funding-phoebe",
    parentId: null,
    name: "Funding Phoebe",
    avatarEmoji: "📊",
    personaVoiceKey: "funding-phoebe",
    strategyKey: "funding-phoebe",
    config: {
      fundingThreshold: 0.0001,
      exitFavorablePct: 0.008,
      maxHoldMs: 4 * 60 * 60 * 1000,
      leverage: 20,
    },
    status: "paper",
  },
  {
    id: "funding-phoebe-lite",
    parentId: "funding-phoebe",
    name: "Funding Phoebe Lite",
    avatarEmoji: "📊",
    personaVoiceKey: "funding-phoebe",
    strategyKey: "funding-phoebe-lite",
    config: {
      fundingThreshold: 0.00005,
      exitFavorablePct: 0.005,
      maxHoldMs: 2 * 60 * 60 * 1000,
      leverage: 20,
    },
    status: "paper",
  },
  {
    id: "mean-revert-mike",
    parentId: null,
    name: "Mean-Revert Mike",
    avatarEmoji: "🎯",
    personaVoiceKey: "mean-revert-mike",
    strategyKey: "mean-revert-mike",
    config: {
      timeframe: "1m",
      candleCount: 30,
      zEntryThreshold: 2.5,
      exitFavorablePct: 0.006,
      maxHoldMs: 30 * 60 * 1000,
      leverage: 25,
    },
    status: "paper",
  },
  {
    id: "mean-revert-mike-patient",
    parentId: "mean-revert-mike",
    name: "Mean-Revert Mike Patient",
    avatarEmoji: "🎯",
    personaVoiceKey: "mean-revert-mike",
    strategyKey: "mean-revert-mike-patient",
    config: {
      timeframe: "1h",
      candleCount: 24,
      zEntryThreshold: 3.0,
      exitFavorablePct: 0.012,
      maxHoldMs: 4 * 60 * 60 * 1000,
      leverage: 25,
    },
    status: "paper",
  },
  {
    id: "momo-max",
    parentId: null,
    name: "Momo Max",
    avatarEmoji: "🚀",
    personaVoiceKey: "momo-max",
    strategyKey: "momo-max",
    config: {
      timeframe: "5m",
      candleCount: 12,
      breakoutPct: 0.01,
      volumeMultiplier: 1.5,
      exitFavorablePct: 0.005,
      maxHoldMs: 30 * 60 * 1000,
      leverage: 20,
    },
    status: "paper",
  },
  {
    id: "momo-max-aggressive",
    parentId: "momo-max",
    name: "Momo Max Aggressive",
    avatarEmoji: "🚀",
    personaVoiceKey: "momo-max",
    strategyKey: "momo-max-aggressive",
    config: {
      timeframe: "5m",
      candleCount: 12,
      breakoutPct: 0.005,
      volumeMultiplier: 1.3,
      exitFavorablePct: 0.003,
      maxHoldMs: 20 * 60 * 1000,
      leverage: 20,
    },
    status: "paper",
  },
  {
    id: "vol-vector",
    parentId: null,
    name: "Vol Vector",
    avatarEmoji: "💥",
    personaVoiceKey: "vol-vector",
    strategyKey: "vol-vector",
    config: {
      recentTimeframe: "1m",
      recentCount: 5,
      baselineTimeframe: "1h",
      baselineCount: 24,
      volMultiplier: 1.5,
      trendConsistencyMin: 0.6,
      exitFavorablePct: 0.006,
      maxHoldMs: 15 * 60 * 1000,
      leverage: 30,
    },
    status: "paper",
  },
  {
    id: "vol-vector-hair-trigger",
    parentId: "vol-vector",
    name: "Vol Vector Hair-Trigger",
    avatarEmoji: "💥",
    personaVoiceKey: "vol-vector",
    strategyKey: "vol-vector-hair-trigger",
    config: {
      recentTimeframe: "1m",
      recentCount: 5,
      baselineTimeframe: "1h",
      baselineCount: 24,
      volMultiplier: 1.2,
      trendConsistencyMin: 0.5,
      exitFavorablePct: 0.004,
      maxHoldMs: 10 * 60 * 1000,
      leverage: 30,
    },
    status: "paper",
  },
  {
    id: "boomer-trend",
    parentId: null,
    name: "Boomer Trend",
    avatarEmoji: "🐢",
    personaVoiceKey: "boomer-trend",
    strategyKey: "boomer-trend",
    config: {
      timeframe: "4h",
      candleCount: 30,
      fastPeriod: 7,
      slowPeriod: 21,
      exitFavorablePct: 0.03,
      maxHoldMs: 48 * 60 * 60 * 1000,
      leverage: 10,
    },
    status: "paper",
  },
  {
    id: "boomer-trend-wide",
    parentId: "boomer-trend",
    name: "Boomer Trend Wide",
    avatarEmoji: "🐢",
    personaVoiceKey: "boomer-trend",
    strategyKey: "boomer-trend-wide",
    config: {
      timeframe: "4h",
      candleCount: 40,
      fastPeriod: 12,
      slowPeriod: 36,
      exitFavorablePct: 0.05,
      maxHoldMs: 72 * 60 * 60 * 1000,
      leverage: 10,
    },
    status: "paper",
  },
];

async function main() {
  for (const row of ROWS) {
    await db.insert(bots).values(row).onConflictDoNothing();
  }
  console.log(`seeded ${ROWS.length} bots`);
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
